<!--
    This template file is for the account settings.
    File acts as a view file for our Account.
-->

<?php
    // initialize all values required on this page
    $status = $this->getRegistrationStatus();
    $userEmail = $this->getCurrentAdminUser()->getEmail();

echo'	<div class="row">
	<div class="col-sm-7 page_margin" >  
   <div class="page" id="account">		
            <div class="mosp_table_layout">';

                if($status=='')
                {
                    echo $this->getLayout()
                              ->createBlock("MiniOrange\OAuth\Block\OAuth")
                              ->setTemplate("MiniOrange_OAuth::register.phtml")
                              ->toHtml();
                }
                else
                {

                    echo $this->getLayout()
                              ->createBlock("MiniOrange\OAuth\Block\OAuth")
                              ->setTemplate("MiniOrange_OAuth::profile.phtml")
                              ->toHtml();
                }

echo'       </div>
        </div>';
