<?php

// initialize all variables
$oauthsettings = $this->getExtensionPageUrl('oauthsettings');
$account = $this->getExtensionPageUrl('account');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$rolesettings = $this->getExtensionPageUrl('rolesettings');
$support = $this->getExtensionPageUrl('support');
$pricing = $this->getExtensionPageUrl('upgrade');
$activeTab = $this->getCurrentActiveTab();
echo'	<div style=" padding: 0 1%;">
            <div class="topnav" id="myTopnav">
                <a class="nav-tab '.($activeTab == 'oauthsettings' ? 'active' : '').'" href="'.$oauthsettings.'"> OAuth Settings</a>
                <a class="nav-tab '.($activeTab == 'signinsettings' ? 'active' : '').'" href="'.$signinsettings.'"> Sign In Settings</a>
                <a class="nav-tab '.($activeTab == 'attrsettings' ? 'active' : '').'" href="'.$attrsettings.'"> Attribute Mapping</a>
                <a class="nav-tab '.($activeTab == 'rolesettings' ? 'active' : '').'" href="'.$rolesettings.'"> Role Mapping</a>
                <a class="nav-tab '.($activeTab == 'account' ? 'active' : '').'" href="'.$account.'"> Account</a>
                <a class="nav-tab '.($activeTab == 'upgrade' ? 'active' : '').'" href="'.$pricing.'"> Upgrade</a>
            </div>
        </div>';
