<!--
    This template file is for the OAuth Provider settings.
    File acts as a view file for our OAuth Provider settings.
-->
<?php
    // initialize all values
    $isEnabled = $this->isEnabled() ? "" : "disabled";
    $appName = $this->getAppName();
    $clientID = $this->getClientID();
    $clientSecret = $this->getClientSecret();
    $scope = $this->getScope();
    $authorizeURL = $this->getAuthorizeURL();
    $accessTokenURL = $this->getAccessTokenURL();
    $getUserInfoURL = $this->getUserInfoURL();
    $logoutURL = $this->getLogoutURL();
    $callbackURL = $this->getCallBackUrl();
	$jwksURL = $this ->getJwksUrl();
    $isOAuthConfigured = !$this->isOAuthConfigured() ? 'disabled title="Please Configure an OAuth Provider"' : '';
    $x509Certificate = $this->getX509Cert();
    $isHeader =$this->isHeader() ? "checked" : "";
    $isBody = $this->isBody() ? "checked" : "";
	$disabled = !$isEnabled ? "disabled" : "";
	$testUrl = $this->getTestUrl();
	$formKey = $this->getBlockHtml('formkey');
	$endpoint_url = $this->getConfigUrl();
	$premiumlink = $this->getExtensionPageUrl('upgrade');
	$isJwksUrl = empty($jwksURL) ? "" : "checked";
 	$isCertificate = empty($x509Certificate) ? "" : "checked";
	$grantType= $this->getGrantType();



?>
	<script>
		var testURL = "<?php  echo $testUrl; ?>";
	</script>
	<div class="row">
<div class="col-sm-7">
	<div class="page" id="oauthprovider">
		<div class="mosp_table_layout">
			<form name="f" method="post" action="">
				<?php  echo $formKey; ?>
				<input type="hidden" <?php ; ?> name="option" value="saveOAuthSettings" />
				<h3>CONFIGURE OAUTH</h3>
				<hr>
				<table style="width:100%;">

					<tr>
						<td style="width: 300px !important;"><strong>Callback URL:</strong></td>
						<td>
							<p style="width: 100%;"><?php  echo $callbackURL; ?></p>
						</td>
					</tr>

					<tr>
					<td style="width: 300px !important;"><strong>Setup Guide:</strong></td>
					<td><p style="width: 100%;">Click <a href="https://plugins.miniorange.com/magento-sso-single-sign-on-with-oauth-openid-connect-setup-guides" target="_blank"><bold>here</bold></a> to view the setup guide page.</p>
					</td>
					</tr>

					<tr>
						<td style="width:300px; !important"><strong>OAuth Provider Name<span style="color:red;">*</span>:</strong></td>
						<td><input type="text" <?php ; ?> name="mo_oauth_app_name"
								style="width: 100%;" value="<?php  echo $appName; ?>" required
								pattern="^\w*$" title="Only alphabets, numbers and underscore is allowed"/></td>
					</tr>
					<tr>
						<td style="width: 300px; !important"><strong>Client ID <span style="color:red;">*</span>:</strong></td>
						<td><input type="text" <?php ; ?> name="mo_oauth_client_id" style="width: 100%;"
							value="<?php echo $clientID; ?>" required /></td>
					</tr>
					<tr>
						<td style="width: 300px; !important"><strong>Client Secret <span style="color:red;">*</span>:</strong></td>
						<td><input type="text" <?php ; ?> name="mo_oauth_client_secret" style="width: 100%;"
							value="<?php echo $clientSecret ; ?>" required /></td>
					</tr>
					<tr>
						<td style="width: 300px; !important"><strong>Scope <span style="color:red;">*</span>:</strong></td>
						<td><input type="text"<?php ; ?> name="mo_oauth_scope" style="width: 100%;"
							value="<?php echo $scope ; ?>" required /></td>
					</tr>

					<tr>
						<td style="width: 300px; !important"><strong>End Session Endpoint: </strong></td>
						<td><input type="text"<?php ; ?> name="mo_oauth_end_session_endpoint" style="width: 100%;" $disabled
							value="<?php echo "Available in the PREMIUM version " ; ?>" disabled/></td>
					</tr>

					<input type="hidden" value="<?php echo $grantType ; ?>" name="mo_selected_grant" id="mo_selected_grant" />
					<tr>
					<td style="width: 300px; !important"><strong>Send Client Credentials in:</strong> </td>
					<td><input type="checkbox" <?php ; ?> name="send_header" value="Yes" <?php echo $isHeader ; ?> />Headers
					&nbsp;&nbsp;&nbsp;<input type="checkbox" name="send_body" value="Yes" <?php echo $isBody ; ?>/>Body
					</td>
					</tr>
                    <tr >
                        <td style="width: 300px; !important"><strong>OAuth Endpoints <span style="color:red;">*</span> :</strong></td>
                        <td >
                            <label style="margin-left: 1px"> <input type="radio" <?php ; ?> id="chk_url" name="endpoint_radio_button" value="byurl" onclick="ShowHideDiv()" required> Well-Known Config URL </label>
                            <label style="margin-left: 60px"><input type="radio" <?php ; ?> id="chk_manual" name="endpoint_radio_button" value="bymanual" <?php if($authorizeURL || $accessTokenURL || $getUserInfoURL){ echo 'checked="checked"';}?> onclick="ShowHideDiv()" required >    Enter Endpoints </label>

                        </td>
                    </tr>
                </table>

                <div style="display : none; padding: 8px 0px 10px 0px;" id="endpoint_url">

                    <label class="lable_css_oauthsetting" style="margin-left: 10px;"> <strong>Well-Known Config URL<span style="color:red;">*</span>:</strong></label>
                    <input  type="url" name="endpoint_url" class="input_css_oauthsetting" id="endpoint_url" value="<?php echo $endpoint_url ; ?> "  >
                </div>


                <div style="<?php if($authorizeURL || $accessTokenURL || $getUserInfoURL){echo 'display : block';}else{ echo 'display : none';}?>;" id="mo_oauth_authorize_url" >
                    <div style="padding: 8px 0px 5px 10px;">

                        <label class="lable_css_oauthsetting" ><strong>Authorization Endpoint<span style="color:red;">*</span>:</strong></label>
                        <input class="input_css_oauthsetting" type="url" <?php ; ?> name="mo_oauth_authorize_url"  value="<?php echo $authorizeURL ; ?> " >

                    </div><br>
                    <div style="padding: 0px 0px 5px 10px">
                        <label class="lable_css_oauthsetting" ><strong>AccessToken Endpoint<span style="color:red;">*</span>:</strong></label>
                        <input class="input_css_oauthsetting" type="url" <?php ; ?> name="mo_oauth_accesstoken_url"  value="<?php echo $accessTokenURL ; ?> "  >
                    </div><br>
                    <div style="padding: 0px 0px 0px 10px">
                        <label class="lable_css_oauthsetting" ><strong>Get User Info Endpoint<span style="color:red;">*</span>:</strong></label>
                        <input class="input_css_oauthsetting" type="url" <?php ; ?> name="mo_oauth_getuserinfo_url"  value="<?php echo $getUserInfoURL ; ?> " >
                    </div><br>
                </div>



					<div style="padding:10px 0px 5px 0px;margin-left: 10px ;">
						<strong >Grant Type:</strong>


							<select name="mo_oauth_grant_type" <?php ; ?> id="mo_oauth_grant_type"  style="width: 30%;padding: 6px;margin-left: 87px">
								<option  value="authorization_code" <?php if($grantType=='authorization_code'){echo 'selected';}?>>Authorization Code Grant</option>
								<option  value="implicit_grant" <?php if($grantType=='implicit_grant'){echo 'selected';}?>>Implicit Grant</option>
								<option  value="hybrid_grant" <?php if($grantType=='hybrid_grant'){echo 'selected';}?>>Hybrid Grant</option>
								<option  value="password_grant" <?php if($grantType=='password_grant'){echo 'selected';}?>>Password Grant</option>
								<option  value="client_credentials_grant" <?php if($grantType=='client_credentials_grant'){ echo 'selected';} ?>> Client Credentials Grant</option>
							</select>
</div>
															<!-- OPENID FLOW -->
					<div style="padding:10px 0px 5px 0px;margin-left: 10px ;">

</div>
							<div class="jwks_url" style="padding-top: 10px" >
								<lable style="margin-left:10px"><strong>JWKS URL:</strong></lable>
								<input type="url" name="mo_oauth_jwks_url" disabled style="width: 74% ;padding: 8px;margin-left: 97px;border-color: #eee ;box-shadow: 3px 2px 4px #ebebeb; border: 1px solid #B7B5B5" value="<?php echo "Available in the PREMIUM version " ; ?>">
							</div>


                	<script>
    				 function radio_click()
    				 {
    				 	var cert = document.getElementsByName('cert');
              			for(i = 0; i < cert.length; i++) {
			                if(cert[i].checked){
			                	if(cert[i].value=="jwks_url"){
			                		document.getElementsByClassName('upload_cert')[0].style.display = 'none';
			                		document.getElementsByClassName('jwks_url')[0].style.display = 'block';
			                	}
			                	else{
			                		document.getElementsByClassName('jwks_url')[0].style.display = 'none';
			                		document.getElementsByClassName('upload_cert')[0].style.display = 'block';
			                	}
			                }
			            }
    				 }
			        </script>

					<div style="margin-left:210px">
						<br /><input class="btn-round" type="submit" <?php ; ?> name="submit" style="width:100px;" value="Save" class="button button-primary button-large"
							/> &nbsp;
							<input class="btn-round" type="button" name="test"<?php ; ?> title="You can only test your Configuration after saving your Service Provider Settings."
								onclick="showTestWindow();" <?php echo $isOAuthConfigured ; ?> value="Test configuration" style="width:150px"/>
					</div>
			</form>
		</div>
	</div>
		<script>
		var objSelect = document.getElementById("mo_selected_grant");
		$("#mo_oauth_grant_type").find("option[value="' + value + '"]").prop("selected",true);
	</script>

<style>
    .lable_css_oauthsetting{
        display: inline-block;
        width: 166px;
        word-wrap: break-word;
    }
    .input_css_oauthsetting{
        width: 74%;
        padding: 8px;
        margin-left: 1px;
        border-color: #eee ;
        box-shadow: 3px 2px 4px #ebebeb;
        border: 1px solid #B7B5B5
    }
    </style>

    <script type="text/javascript">
        function ShowHideDiv() {
            var chk_url = document.getElementById("chk_url");

            var endpoint_url = document.getElementById("endpoint_url");
            endpoint_url.style.display = chk_url.checked ? "block" : "none";


            var chk_manual = document.getElementById("chk_manual");


            var mo_oauth_authorize_url= document.getElementById("mo_oauth_authorize_url");
            mo_oauth_authorize_url.style.display = chk_manual.checked ? "block" : "none";


        }
    </script>


