<?php
// initialize all variables
$oauthsettings = $this->getExtensionPageUrl('oauthsettings');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$support = $this->getExtensionPageUrl('support');
$formKey = $this->getBlockHtml('formkey');

echo '
        <div id="userprofile">
            <div style="display: flow-root;">
                <div style="float:left;"><h3>Your Profile</h3></div>

                <form name="f" method="post" action="">
                    '.$formKey.'
                    <input type="hidden" name="option" value="removeAccount" >  
                    <input type="submit" class="btn-round" style="float:right;" name="submit" id="remove_plugin" value="Remove Account"> 
                </form>
            </div>
            <hr>
            <table class="data center">
                <tr>
                    <td><b>miniOrange Account Email</b></td>
                    <td>'.$this->getCustomerEmail().'</td>
                </tr>
                <tr>
                    <td><b>Customer ID</b></td>
                    <td>'.$this->getCustomerKey().'</td>
                </tr>
                <tr>
                    <td><b>API Key</b></td>
                    <td>'.$this->getApiKey().'</td>
                </tr>
                <tr>
                    <td><b>Token Key</b></td>
                    <td>'.$this->getToken().'</td>
                </tr>
            </table>
        </div>
        <br>
         <div class="mo_note" id="configure">
            <div class="btn-link" id="configure">How do I configure the module?</a></div>
            <div style="display:none" class="show_info">
                <b>The module has step by step instructions on each page to help you. Follow these steps:</b><br>
                 <ol>
                    <li>Go to the OAuth Provider Section of the module or <a href="'.$oauthsettings.'">click here</a>. On this page,
                    configure your OAuth Provider.</li>
                    <li>After your OAuth Provider is configured, Click on the Test Configuration button on the same page to test your settings.</li>
                    <li>After successful setup, Go to the Attribute / Role Mapping section of the module or <a href="'.$attrsettings.'">click here</a>.
                    You will need to configure the username and email attribute from the OAuth Provider here.</li>
                    <li>Go to the Sign In Settings section of the module or <a href="'.$signinsettings.'">click here</a>. 
                        Here decide how you wish for your users to do SSO.</li>
                    <li>Logout and do a final Test.</li>
                </ol>
            </div>
        </div>
        <div class="mo_note">
            <div class="btn-link" id="new_to_saml" href="">I am new to SAML and I don\'t know how to configure the plugin!</a></div>
            <div style="display:none" class="show_info">
                Drop us a query from the support page or an email at 
                magentosupport@xecurify.com and we will get in touch to help you setup the module and site for SSO. 
            </div>';
