    <!--Pricing Tab-->
    <?php

    $idpsettings = $this->getExtensionPageUrl('idpsettings');
    $hostname = $this->getMiniOrangeUrl();
    $email = $this->getCustomerEmail();
    $version = $this->getCurrentVersion();




    echo '
    <div class="page" id="pricing">
    <section class="pricing py-5">
    <div class="container">
      <div class="row">
        <!-- Free Tier -->

       <div class="columns">
         <ul class="price">
           <li class="header" style="background-color: #ea680b">Basic <small>'.$version.'</small> [Current Plan]</li>
           <li class="grey">$0</li>
           <li>&#9989; Basic Attribute Mapping</li>
           <li>&#9989; Auto Create Users (Upto 10 users)</li>
           <li>&#9989; Add SSO login button</li>
           <li>&#10060; <s>Oauth Single Logout</s></li>
           <li>&#10060; <s>Auto redirect / Protect your complete site</s></li>
           <li>&#10060; <s>Advanced Attribute Mapping</s></li>
           <li>&#10060; <s>Custom Attribute Mapping</s></li>
           <li>&#10060; <s>Advanced Role Mapping</s></li>
           <li>&#10060; <s>Admin SSO</s></li>
           <li>&#10060; <s>Support for multi-store</s></li>
           <li>&#10060; <s>Support for multi-site</s></li>
           <li><a href="#" class="button btn-round" style="margin-left:70px;font: size 14px;px;padding:7px 12px" >Upgrade</a>
         </ul>
       </div>

       <div class="columns">
         <ul class="price">
           <li class="header">Standard</li>
           <li class="grey">$349*</li>
           <li>&#9989; Basic Attribute Mapping</li>
             <li>&#9989; Auto Create Users (Unlimited)</li>
             <li>&#9989; Add SSO login button</li>
             <li>&#9989; Oauth Single Logout</li>
             <li>&#9989; Auto redirect / Protect your complete site</li>
             <li>&#9989; Advanced Attribute Mapping</li>
             <li>&#10060; <s>Custom Attribute Mapping</s></li>
             <li>&#10060; <s>Advanced Role Mapping</s></li>
             <li>&#10060; <s>Admin SSO</s></li>
             <li>&#10060; <s>Support for multi-store</s></li>
             <li>&#10060; <s>Support for multi-site</s></li>
           <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+OAuth+Standard+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+OAuth+Standard+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a> 
           <a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+Request+Free+Trial+of+Magento+OAuth+Standard+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+request+a+7-day+Free+trial+of+the+Magento+OAuth+Standard+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Free Trial</a>
           </li>
          </ul>
       </div>

       <div class="columns">
         <ul class="price">
             <li class="header">Premium</li>
             <li class="grey">$449*</li>
             <li>&#9989; Basic Attribute Mapping</li>
             <li>&#9989; Auto Create Users (Unlimited)</li>
             <li>&#9989; Add SSO login button</li>
             <li>&#9989; Oauth Single Logout</li>
             <li>&#9989; Auto redirect / Protect your complete site</li>
             <li>&#9989; Advanced Attribute Mapping</li>
             <li>&#9989; Custom Attribute Mapping</li>
             <li>&#9989; Advanced Role Mapping</li>
             <li>&#9989; Admin SSO</li>
             <li>&#9989; Support for multi-store</li>
             <li>&#10060; <s>Support for multi-site</s></li>
             <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+OAuth+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+OAuth+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
             <a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+Request+Free+Trial+of+Magento+OAuth+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+request+a+7-day+Free+trial+of+Magento+OAuth+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Free Trial</a>
             </li>
         </ul>
       </div>

          <div class="columns">
             <ul class="price">
             <li class="header">Enterprise</li>
             <li class="grey">$649*</li>
             <li>&#9989; Basic Attribute Mapping</li>
             <li>&#9989; Auto Create Users (Unlimited)</li>
             <li>&#9989; Add SSO login button</li>
             <li>&#9989; Oauth Single Logout</li>
             <li>&#9989; Auto redirect / Protect your complete site</li>
             <li>&#9989; Advanced Attribute Mapping</li>
             <li>&#9989; Custom Attribute Mapping</li>
             <li>&#9989; Advanced Role Mapping</li>
             <li>&#9989; Admin SSO</li>
             <li>&#9989; Support for multi-store</li>
             <li>&#9989; Support for multisites**   (2 subsites)</li>
                
                  <li><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+OAuth+Enterprise+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+OAuth+Enterprise+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
                  <a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+Request+Free+Trial+of+Magento+OAuth+Enterprise+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+request+a+7-day+Free+trial+of+Magento+OAuth+Enterprise+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Free Trial</a>
                  </li>
              </ul>
              </div>
   </div>

   <div style="margin:2% 0 2% 2%;">
      <form style="display:none;" id="mocf_loginform" action="'.$hostname.'/moas/login"
          target="_blank" method="post">
          <input type="email" name="username" value="'.$email.'" >
          <input type="text" name="redirectUrl" value="'.$hostname.'/moas/initializepayment" >
          <input type="text" name="requestOrigin" id="requestOrigin"  >
      </form>
  </div>
    </div>

  </section>
    </div>

<div>
<p>* Cost applicable for one instance only. Licenses are perpetual and the Support Plan includes 12 months of maintenance (support and version updates). You can renew maintenance after 12 months at 50% of the current license cost.</p><br>

<p>** Multiple Sites Supported
There is an additional cost for the sites if the number of sites is more than 2.</p><br>


<p>Multiple IDPs Supported
We can configure multiple IDPs with our miniOrange cloud. Contact us at <a href="mailto:magentosupport@xecurify.com">magentosupport@xecurify.com</a> for more info.</p><br>


</div>


    ';
